config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount SimpleDiscussion::Engine => "/forum", constraints: -> { Flipper.enabled?(:forum) }

  require "sidekiq/web"

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  # resources :assignment_submissions
  resources :group_members, only: %i[create destroy]
  resources :groups, except: %i[index] do
    resources :assignments, except: %i[index]
  end

  resources :custom_mails, except: %i[destroy]
  get "/custom_mails/send_mail/:id", to: "custom_mails#send_mail", as: "send_custom_mail"
  get "/custom_mails/send_mail_to_self/:id", to: "custom_mails#send_mail_self",
                                             as: "send_custom_mail_self"

  # grades
  scope "/grades" do
    post "/", to: "grades#create", as: "grades"
    delete "/", to: "grades#destroy"
    get "/to_csv/:assignment_id", to: "grades#to_csv", as: "grades_to_csv"
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/search", to: "search#search"

  resources :about, only: :index
  resources :privacy, only: :index

  scope "/groups" do
    get "/:group_id/assignments/:id/reopen", to: "assignments#reopen", as: "reopen_group_assignment"
    get "/:group_id/assignments/:id/start", to: "assignments#start", as: "assignment_start"
  end
  resources :stars, only: %i[create destroy]

  resources :featured_circuits, only: %i[index create]
  delete "/featured_circuits", to: "featured_circuits#destroy"

  get "/users/edit", to: redirect('/')
  devise_for :users, controllers: {
    registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  # Logix web pages resources
  root "logix#index"
  get  "/examples", to: "logix#examples"
  get  "/tos", to: "logix#tos"
  get  "/teachers", to: "logix#teachers"
  get  "/contribute", to: "logix#contribute"

  #announcements
  resources :announcements, except: %i[show]

  # users

  notify_to :users, controller: "users/notifications"

  scope "/users" do
    get "/:id/profile", to: redirect('/users/%{id}'), as: "profile"
    get "/:id/profile/edit", to: "users/logix#edit", as: "profile_edit"
    patch "/:id/update", to: "users/logix#update", as: "profile_update"
    get "/:id/groups", to: "users/logix#groups", as: "user_groups"
    get "/:id/", to: "users/logix#index", as: "user_projects"
    get "/educational_institute/typeahead/:query" => "users/logix#typeahead_educational_institute"
    get "/:id/notifications", to: "users/notifications#index", as: "notifications"
  end

  post "/push/subscription/new", to: "push_subscription#create"
  post "/push/test", to: "push_subscription#test"

  # projects
  scope "/projects" do
    get "/create_fork/:id", to: "projects#create_fork", as: "create_fork_project"
    get "/change_stars/:id", to: "projects#change_stars", as: "change_stars"
    get "tags/:tag", to: "projects#get_projects", as: "tag"
  end

  mount Commontator::Engine => "/commontator"

  # simulator
  scope "/simulator" do
    get "/:id", to: "simulator#show", as: "simulator"
    get "/edit/:id", to: "simulator#edit", as: "simulator_edit"
    post "/get_data", to: "simulator#get_data"
    post "/post_issue", to: "simulator#post_issue"
    post "/update_data", to: "simulator#update"
    post "/update_image", to: "simulator#update_image"
    post "/create_data", to: "simulator#create"
    post "/verilogcv", to: "simulator#verilog_cv"
    get "/", to: "simulator#new", as: "simulator_new"
    get "/embed/:id", to: "simulator#embed", as: "simulator_embed"
  end

  scope "/simulator_old" do
    get "/:id", to: "simulator_old#show", as: "simulator_old"
    get "/edit/:id", to: "simulator_old#edit", as: "simulator_old_edit"
    post "/get_data", to: "simulator_old#get_data"
    post "/post_issue", to: "simulator_old#post_issue"
    post "/update_data", to: "simulator_old#update"
    post "/update_image", to: "simulator_old#update_image"
    post "/create_data", to: "simulator_old#create"
    post "/verilogcv", to: "simulator_old#verilog_cv"
    get "/", to: "simulator_old#new", as: "simulator_old_new"
    get "/embed/:id", to: "simulator_old#embed"
  end
  # get 'simulator/embed_cross/:id', to: 'simulator#embed_cross', as: 'simulator_embed_cross'

  resources :users do
    resources :projects, except: %i[index]
  end
  resources :collaborations, only: %i[create destroy update]

  # redirects
  get "/facebook", to: redirect("https://www.facebook.com/CircuitVerse")
  get "/twitter", to: redirect("https://www.twitter.com/CircuitVerse")
  get "/linkedin", to: redirect("https://www.linkedin.com/company/circuitverse")
  get "/slack", to: redirect(
    "https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE"
  )
  get "/discord", to: redirect("https://discord.gg/8G6TpmM")
  get "/github", to: redirect("https://github.com/CircuitVerse")
  get "/learn", to: redirect("https://learn.circuitverse.org")
  get "/docs", to: redirect("https://docs.circuitverse.org")
  get "/features", to: redirect("/#home-features-section")

  # get 'comments/create_reply/:id', to: 'comments#create_reply', as: 'reply_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      post "/auth/login", to: "authentication#login"
      post "/auth/signup", to: "authentication#signup"
      post "/oauth/login", to: "authentication#oauth_login"
      post "/oauth/signup", to: "authentication#oauth_signup"
      get  "/public_key.pem", to: "authentication#public_key"
      post "/password/forgot", to: "authentication#forgot_password"
      get "/me", to: "users#me"
      post "/forgot_password", to: "users#forgot_password"
      resources :users, only: %i[index show update]
      get "/projects/featured", to: "projects#featured_circuits"
      resources :projects, only: %i[index show update destroy] do
        member do
          get "toggle-star", to: "projects#toggle_star"
          get "fork", to: "projects#create_fork"
          get "image_preview", to: "projects#image_preview"
        end
        resources :collaborators, only: %i[index create destroy]
      end
      resources :users do
        member do
          get "projects", to: "projects#user_projects"
          get "favourites", to: "projects#user_favourites"
        end
      end
      post "/assignments/:assignment_id/projects/:project_id/grades", to: "grades#create"
      resources :grades, only: %i[update destroy]
      get "/groups/mentored", to: "groups#groups_mentored"
      resources :groups, only: %i[index show update destroy]
      delete "/group/members/:id", to: "group_members#destroy"
      resources :groups do
        resources :members, controller: "group_members", shallow: true, only: %i[index create]
        resources :assignments, shallow: true
      end
      resources :assignments do
        member do
          patch "reopen"
          patch "start"
        end
      end
      resources :threads, only: %i[close reopen] do
        resources :comments, only: %i[index create update], shallow: true do
          member do
            put "upvote"
            put "downvote"
            put "unvote"

            put "delete"
            put "undelete"
          end
        end

        member do
          put "close"
          put "reopen"

          put "subscribe"
          put "unsubscribe"
        end
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/logix_controller.rb
# frozen_string_literal: true

class LogixController < ApplicationController

  MAXIMUM_FEATURED_CIRCUITS = 3

  def index
    @projects = Project.select(:id, :author_id, :image_preview, :name, :slug)
                       .public_and_not_forked
                       .where.not(image_preview: "default.png")
                       .order(id: :desc)
                       .limit(Project.per_page)

    page = params[:page].to_i
    @projects = if page.positive?
      @projects.paginate(page: page)
    else
      @projects.paginate(page: nil)
    end

    @featured_circuits = Project.joins(:featured_circuit)
      .order("featured_circuits.created_at DESC")
                                .limit(MAXIMUM_FEATURED_CIRCUITS)

    respond_to do |format|
      format.html
      format.json { render json: @projects }
      format.js
    end
  end

  def examples
    @examples = [{ name: "Full Adder from 2-Half Adders", id: "users/3/projects/247",
                   img: "examples/fullAdder_n.jpg" },
                 { name: "16 Bit ripple carry adder", id: "users/3/projects/248",
                   img: "examples/RippleCarry_n.jpg" },
                 { name: "Asynchronous Counter", id: "users/3/projects/249",
                   img: "examples/AsyncCounter_n.jpg" },
                 { name: "Keyboard", id: "users/3/projects/250",
                   img: "examples/Keyboard_n.jpg" },
                 { name: "FlipFlop", id: "users/3/projects/251",
                   img: "examples/FlipFlop_n.jpg" },
                 { name: "ALU 74LS181 by Ananth Shreekumar", id: "users/126/projects/252",
                   img: "examples/ALU_n.jpg" }]
  end

  def tos; end

  def teachers; end

  def contribute; end
end

app/controllers/users/logix_controller.rb
# frozen_string_literal: true

class Users::LogixController < ApplicationController
  TYPEAHEAD_INSTITUTE_LIMIT = 50

  include UsersLogixHelper

  before_action :authenticate_user!, only: %i[edit update groups]
  before_action :set_user, except: [:typeahead_educational_institute]

  def index; end

  def favourites
    @projects = @user.rated_projects
  end

  def profile
    @profile = ProfileDecorator.new(@user)
  end

  def edit; end

  def typeahead_educational_institute
    query = params[:query]
    institute_list = User.where("educational_institute LIKE :query", query: "%#{query}%")
                         .distinct
                         .limit(TYPEAHEAD_INSTITUTE_LIMIT)
                         .pluck(:educational_institute)
    typeahead_array = institute_list.map { |item| { name: item } }
    render json: typeahead_array
  end

  def update
    if @profile.update(profile_params)
      redirect_to profile_path(current_user)
    else
      render :edit
    end
  end

  def groups
    @user = authorize @user
    @groups_mentored = Group.where(id: Group.joins(:mentor).where(mentor: @user))
                            .select("groups.*, COUNT(group_members.id) as group_member_count")
                            .joins("left outer join group_members on \
                              (group_members.group_id = groups.id)")
                            .group("groups.id")
  end

  private

    def profile_params
      params.require(:user).permit(:name, :profile_picture, :country, :educational_institute,
                                   :subscribed)
    end

    def set_user
      @profile = current_user
      @user = User.find(params[:id])
    end
end

app/views/logix/index.html.erb
<script>
  $(document).ready(function(){
    $("#alertdiv").delay(5000).fadeOut(600);
  });
</script>

<% content_for :title, "CircuitVerse - Online Digital Logic Circuit Simulator" %>

<% set_meta_tags twitter: {
  card: "summary_large_image",
  title: yield(:title),
  description: Rails.configuration.site_description,
  image: {
    src: "#{Rails.configuration.site_url}img/logixBanner2.png"
  }
} %>

<% set_meta_tags og: {
  title: yield(:title),
  image: "#{Rails.configuration.site_url}img/logixBanner2.png",
  description: Rails.configuration.site_description,
  type: "article",
  site_name: Rails.configuration.site_name
} %>

    <% if notice %>
    <div class="row" id='alertdiv'>
      <div class="alert alert-success alert-dismissible container text-center">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h6><%= notice %></h6>
      </div>
    </div>
    <% end %>
    <%= render "announcements/announcement" %>
    <div class="container">
      <div class="row center-row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <div class="home-main-content">
            <h1>Dive into the world of Logic Circuits for free!</h1><br>
            <p>From simple gates to complex sequential circuits, plot timing diagrams, automatic circuit generation, explore standard ICs, and much more</p>
            <div class="home-buttons-container justify-content-center">
              <a class="btn primary-button home-simulator-button" href='/simulator'>Launch Simulator</a> &nbsp;
              <a href="https://learn.circuitverse.org/" class="anchor-text">Learn Logic Design</a>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag "homepage/new_homepage_sketch.png", alt: "HomepageSketch", :class => "home-image-cover" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 home-tertiary-button-container">
          <a class="btn tertiary-button" href="/teachers">For Teachers</a>
          <a class="btn tertiary-button" href="/contribute">For Contributors</a>
        </div>
      </div>
      <div id="home-features-section" class="row center-row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h3>Features</h3>
          <p>Design circuits quickly and easily with a modern and intuitive user interface with drag-and-drop, copy/paste, zoom and more.</p>
        </div>
      </div>
      <div class="row center-row justify-content-center">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card home-feature-card">
            <%= image_tag "homepage/export-hd.png", alt: "Export HD", :class => "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Export High-Resolution Images</h5>
              <p class="card-text">CircuitVerse can export high resolution images in multiple formats including SVG.</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card home-feature-card">
            <%= image_tag "homepage/combinations analysis.png", alt: "Combinational Analysis", :class => "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Combinational Analysis</h5>
              <p class="card-text">Automatically generate circuit based on truth table data. This is great to create complex logic circuits and can be easily be made into a subcircuit.</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-s-12 col-md-6 col-lg-4">
          <div class="card home-feature-card">
            <%= image_tag "homepage/embed.png", alt: "Embed", :class => "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Embed in Blogs</h5>
              <p class="card-text">Since CircuitVerse is built in HTML5, an iFrame can be generated for each project allowing the user to embed it almost anywhere.</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card home-feature-card">
            <%= image_tag "homepage/sub-circuit.png", alt: "Sub Circuit", :class => "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Use Sub circuits</h5>
              <p class="card-text">Create subcircuits once and use them repeatedly. This allows easier and more structured design.</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card home-feature-card">
            <%= image_tag "homepage/multi-bit-bus.png", alt: "Multi Bit Bus", :class => "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Multi Bit Buses and components</h5>
              <p class="card-text">CircuitVerse supports multi bit wires, this means circuit design is easier, faster and uncluttered.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row center-row home-circuit-card-row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h3>Featured Examples</h3>
          <p>Learn and get inspired from the best examples</p>
        </div>
      </div>
      <div class="row center-row justify-content-center">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card circuit-card">
            <%= image_tag "homepage/rippleCarry.jpg", alt: "Ripple Carry", :class => "card-img-top circuit-card-image examples-circuit-card-image" %>
            <div class="card-footer circuit-card-footer">
              <div class="circuit-card-name">
                <p>16-bit Ripple Carry Adder</p>
              </div>
              <a class="btn primary-button circuit-card-primary-button" target="_blank" href="https://circuitverse.org/users/3/projects/248">View</a>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card circuit-card">
            <%= image_tag "homepage/sap.jpg", alt: "SAP-1", :class => "card-img-top circuit-card-image examples-circuit-card-image" %>
            <div class="card-footer circuit-card-footer">
              <div class="circuit-card-name">
                <p>SAP-1</p>
              </div>
              <a class="btn primary-button circuit-card-primary-button" target="_blank" href="https://circuitverse.org/users/3/projects/67">View</a>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card circuit-card">
            <%= image_tag "homepage/fullAdder.jpg", alt: "Full Adder", :class => "card-img-top circuit-card-image examples-circuit-card-image" %>
            <div class="card-footer circuit-card-footer">
              <div class="circuit-card-name">
                <p>Full Adder from 2 Half Adders</p>
              </div>
              <a class="btn primary-button circuit-card-primary-button" target="_blank" href="https://circuitverse.org/users/3/projects/247">View</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row center-row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <a class="btn primary-button homepage-primary-button-feature" href="/examples">Explore More</a>
        </div>
      </div>
    </div>
    <div class="container-fluid home-container-fluid">
      <div class="container">
        <div class="row center-row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h3>Editor Picks</h3>
            <p>These circuits have been hand-picked by our authors for their awesomeness</p>
          </div>
        </div>
        <div class="row center-row justify-content-center">
          <% @featured_circuits.each do |circuit| %>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
              <div class="card circuit-card">
                <%= image_tag circuit.image_preview.url, alt: circuit.name, :class => "card-img-top circuit-card-image" %>
                <div class="card-footer circuit-card-footer">
                  <div class="circuit-card-name">
                    <p><%= circuit.name %></p>
                  </div>
                  <a class="btn primary-button circuit-card-primary-button" target="_blank" href="<%= user_project_url(circuit.author, circuit) %>">View</a>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row center-row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <a class="btn primary-button homepage-primary-button-feature" href="/featured_circuits">Explore More</a>
            </div>
        </div>
      </div>
    </div>
    <div class="container" id="recent">
      <div class="row center-row home-circuit-card-row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h3>Recent Circuits</h3>
          <p>Explore the latest circuits by our awesome users</p>
        </div>
      </div>
      <div class="row center-row justify-content-center">
        <% @projects.each do |project| %>
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
            <div class="card circuit-card">
              <%= image_tag project.image_preview.url, alt: project.name, :class => "card-img-top circuit-card-image" %>
              <div class="card-footer circuit-card-footer">
                <div class="circuit-card-name">
                  <p><%= project.name %></p>
                </div>
                <a class="btn primary-button circuit-card-primary-button" target="_blank" href="<%= user_project_url(project.author, project) %>">View</a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="container pagination-cont">
        <%= will_paginate @projects, renderer: PaginateRenderer %>
      </div>
    </div>

    <% if user_signed_in? %>
    <script>
        if(localStorage.getItem("recover_login")){
            window.location.href = "/simulator"
        }
    </script>
    <% end %>

<script type="application/ld+json">
  {
    "@context" : "http://schema.org",
    "@type" : "WebApplication",
    "name" : "<%= Rails.configuration.site_name %>",
    "image" : "<%= Rails.configuration.site_image %>",
    "url" : "<%= Rails.configuration.site_url %>",
    "applicationCategory" : "<%= Rails.configuration.site_category %>",
    "downloadUrl" : "<%= Rails.configuration.site_download_url %>",
    "operatingSystem": "All"
  }
</script>
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "url" : "<%= Rails.configuration.site_url %>",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "<%= Rails.configuration.site_url %>/search?resource=Projects&q={search_term_string}",
      "query-input": "required name=search_term_string"
    }
  }
</script>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->