config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount SimpleDiscussion::Engine => "/forum", constraints: -> { Flipper.enabled?(:forum) }

  require "sidekiq/web"

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  # resources :assignment_submissions
  resources :group_members, only: %i[create destroy]
  resources :groups, except: %i[index] do
    resources :assignments, except: %i[index]
  end

  resources :custom_mails, except: %i[destroy]
  get "/custom_mails/send_mail/:id", to: "custom_mails#send_mail", as: "send_custom_mail"
  get "/custom_mails/send_mail_to_self/:id", to: "custom_mails#send_mail_self",
                                             as: "send_custom_mail_self"

  # grades
  scope "/grades" do
    post "/", to: "grades#create", as: "grades"
    delete "/", to: "grades#destroy"
    get "/to_csv/:assignment_id", to: "grades#to_csv", as: "grades_to_csv"
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/search", to: "search#search"

  resources :about, only: :index
  resources :privacy, only: :index

  scope "/groups" do
    get "/:group_id/assignments/:id/reopen", to: "assignments#reopen", as: "reopen_group_assignment"
    get "/:group_id/assignments/:id/start", to: "assignments#start", as: "assignment_start"
  end
  resources :stars, only: %i[create destroy]

  resources :featured_circuits, only: %i[index create]
  delete "/featured_circuits", to: "featured_circuits#destroy"

  get "/users/edit", to: redirect('/')
  devise_for :users, controllers: {
    registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  # Logix web pages resources
  root "logix#index"
  get  "/examples", to: "logix#examples"
  get  "/tos", to: "logix#tos"
  get  "/teachers", to: "logix#teachers"
  get  "/contribute", to: "logix#contribute"

  #announcements
  resources :announcements, except: %i[show]

  # users

  notify_to :users, controller: "users/notifications"

  scope "/users" do
    get "/:id/profile", to: redirect('/users/%{id}'), as: "profile"
    get "/:id/profile/edit", to: "users/logix#edit", as: "profile_edit"
    patch "/:id/update", to: "users/logix#update", as: "profile_update"
    get "/:id/groups", to: "users/logix#groups", as: "user_groups"
    get "/:id/", to: "users/logix#index", as: "user_projects"
    get "/educational_institute/typeahead/:query" => "users/logix#typeahead_educational_institute"
    get "/:id/notifications", to: "users/notifications#index", as: "notifications"
  end

  post "/push/subscription/new", to: "push_subscription#create"
  post "/push/test", to: "push_subscription#test"

  # projects
  scope "/projects" do
    get "/create_fork/:id", to: "projects#create_fork", as: "create_fork_project"
    get "/change_stars/:id", to: "projects#change_stars", as: "change_stars"
    get "tags/:tag", to: "projects#get_projects", as: "tag"
  end

  mount Commontator::Engine => "/commontator"

  # simulator
  scope "/simulator" do
    get "/:id", to: "simulator#show", as: "simulator"
    get "/edit/:id", to: "simulator#edit", as: "simulator_edit"
    post "/get_data", to: "simulator#get_data"
    post "/post_issue", to: "simulator#post_issue"
    post "/update_data", to: "simulator#update"
    post "/update_image", to: "simulator#update_image"
    post "/create_data", to: "simulator#create"
    post "/verilogcv", to: "simulator#verilog_cv"
    get "/", to: "simulator#new", as: "simulator_new"
    get "/embed/:id", to: "simulator#embed", as: "simulator_embed"
  end

  scope "/simulator_old" do
    get "/:id", to: "simulator_old#show", as: "simulator_old"
    get "/edit/:id", to: "simulator_old#edit", as: "simulator_old_edit"
    post "/get_data", to: "simulator_old#get_data"
    post "/post_issue", to: "simulator_old#post_issue"
    post "/update_data", to: "simulator_old#update"
    post "/update_image", to: "simulator_old#update_image"
    post "/create_data", to: "simulator_old#create"
    post "/verilogcv", to: "simulator_old#verilog_cv"
    get "/", to: "simulator_old#new", as: "simulator_old_new"
    get "/embed/:id", to: "simulator_old#embed"
  end
  # get 'simulator/embed_cross/:id', to: 'simulator#embed_cross', as: 'simulator_embed_cross'

  resources :users do
    resources :projects, except: %i[index]
  end
  resources :collaborations, only: %i[create destroy update]

  # redirects
  get "/facebook", to: redirect("https://www.facebook.com/CircuitVerse")
  get "/twitter", to: redirect("https://www.twitter.com/CircuitVerse")
  get "/linkedin", to: redirect("https://www.linkedin.com/company/circuitverse")
  get "/slack", to: redirect(
    "https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE"
  )
  get "/discord", to: redirect("https://discord.gg/8G6TpmM")
  get "/github", to: redirect("https://github.com/CircuitVerse")
  get "/learn", to: redirect("https://learn.circuitverse.org")
  get "/docs", to: redirect("https://docs.circuitverse.org")
  get "/features", to: redirect("/#home-features-section")

  # get 'comments/create_reply/:id', to: 'comments#create_reply', as: 'reply_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      post "/auth/login", to: "authentication#login"
      post "/auth/signup", to: "authentication#signup"
      post "/oauth/login", to: "authentication#oauth_login"
      post "/oauth/signup", to: "authentication#oauth_signup"
      get  "/public_key.pem", to: "authentication#public_key"
      post "/password/forgot", to: "authentication#forgot_password"
      get "/me", to: "users#me"
      post "/forgot_password", to: "users#forgot_password"
      resources :users, only: %i[index show update]
      get "/projects/featured", to: "projects#featured_circuits"
      resources :projects, only: %i[index show update destroy] do
        member do
          get "toggle-star", to: "projects#toggle_star"
          get "fork", to: "projects#create_fork"
          get "image_preview", to: "projects#image_preview"
        end
        resources :collaborators, only: %i[index create destroy]
      end
      resources :users do
        member do
          get "projects", to: "projects#user_projects"
          get "favourites", to: "projects#user_favourites"
        end
      end
      post "/assignments/:assignment_id/projects/:project_id/grades", to: "grades#create"
      resources :grades, only: %i[update destroy]
      get "/groups/mentored", to: "groups#groups_mentored"
      resources :groups, only: %i[index show update destroy]
      delete "/group/members/:id", to: "group_members#destroy"
      resources :groups do
        resources :members, controller: "group_members", shallow: true, only: %i[index create]
        resources :assignments, shallow: true
      end
      resources :assignments do
        member do
          patch "reopen"
          patch "start"
        end
      end
      resources :threads, only: %i[close reopen] do
        resources :comments, only: %i[index create update], shallow: true do
          member do
            put "upvote"
            put "downvote"
            put "unvote"

            put "delete"
            put "undelete"
          end
        end

        member do
          put "close"
          put "reopen"

          put "subscribe"
          put "unsubscribe"
        end
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/views/layouts/_footer.html.erb
<div class="container empty-div">
</div>
<div class="text-white">
  <div class="pl-5 pt-2 container-fluid" style="background: #1c1c1c;">
    <div class="col-12">
      <div class="row mt-3 p-3 text-left">
        <div class="col-lg-3 col-xl-3 mb-3">
          <div class="row">
            <div>
              <a href="/">
                <%= image_tag("cvlogo.svg", class: "logo-bottom", alt: "CircuitVerse logo") %>
              </a>
            </div>
            <div class="d-block d-md-none w-100"></div>
            <div class="d-block d-lg-none w-100"></div>
            <div class="d-none d-xl-block w-100"></div>
            <div class="pt-3">
              <table class="w-100">
                <tr>
                  <p class="mt-2 footer-social">Follow us on:</p>
                </tr>
                <tr>
                  <td class="">
                    <a class="" href="/facebook" target="_blank"><%= image_tag("logos/facebook-logo.png", class: "footer-social-icon pt-2", alt: "Facebook logo") %></a>
                  <td class="">
                    <a class="" href="/twitter" target="_blank"><%= image_tag("logos/twitter-logo.png", class: "footer-social-icon pt-2", alt: "Twitter logo") %></a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="d-block d-sm-none w-100">
        <br>
        </div>
        <div class="col-sm-6 col-lg-4 col-xl-4 mx-auto mb-4">
          <table class="w-100">
            <tr>
              <th>Circuits</th>
              <th>Info</th>
            </tr>
            <tr>
              <td><a class="text-white" href="/simulator">Simulator</a></td>
              <td><a class="text-white" href="/docs" target="_blank">Documentation</a></td>
            </tr>
            <tr>
              <td><a class="text-white" href="/learn" target="_blank">Learn</a></td>
              <td><a class="text-white" href="/contribute">Contribute</a></td>
            </tr>
            <tr>
              <td><a class="text-white" href="/examples">Examples</a></td>
              <td><a class="text-white" href="/teachers">Teachers</a></td>
            </tr>
            <tr>
              <% if user_signed_in? %>
                  <td><a class="text-white" href="<%= user_path(current_user) %>">My Circuits</a></td>
              <% else %>
                  <td><a class="text-white" href="/users/sign_in">Login</a></td> 
              <% end %>
              <td><a class="text-white" href="/about">About</a></td>
            </tr>
          </table>
        </div>
        <div class="col-sm-6 col-lg-5 col-xl-5 mx-auto mb-4">
          <table class="w-100 small">
            <tr>
              <td>Brought to you by:</td>
              <td>Hosting sponsor:</td>
            </tr>
            <tr>
              <td class="py-1">
                <a href="https://www.iiitb.ac.in/" target="_blank">
                  <%= image_tag("footer/iiitb.png", class: "footer-logo", alt: "iiitb Logo") %>
                </a>
              </td>
              <td class="py-1">
                <a href="http://digitalocean.com/" target="_blank">
                  <%= image_tag("footer/DO.png", class: "footer-logo", alt: "DO Logo") %>
                </a>
              </td>
            </tr>
            <tr>
              <td>Marketed by:</td>
              <td>Developed by:</td>
            </tr>
            <tr>
              <td class="py-1">
                <a href="http://www.iiitb.org/" target="_blank">
                  <%= image_tag("footer/istudio.png", class: "footer-logo", alt: "istudio Logo") %>
                </a>
              </td>
              <td class="py-1">
                <a href="http://zense.co.in/" target="_blank">
                  <%= image_tag("footer/zense.png", class: "footer-logo", alt: "Zense Logo") %>
                </a>
              </td>
            </tr>
          </table>
        </div>
        <div class="d-none d-sm-block d-md-none copyright pl-3">Copyright © <script type="text/javascript"> document.write(new Date().getFullYear()); </script> CircuitVerse, All rights reserved.</div>
        <div class="d-block d-sm-none copyright pl-3">Copyright © <script type="text/javascript"> document.write(new Date().getFullYear()); </script> CircuitVerse, All rights reserved.</div>
        <div class="d-none d-sm-none d-md-block d-lg-none copyright pl-3" >Copyright © <script type="text/javascript"> document.write(new Date().getFullYear()); </script> CircuitVerse, All rights reserved.</div>
        <div class="d-none d-sm-none d-md-none d-lg-block d-xl-none copyright pl-3" >Copyright © <script type="text/javascript"> document.write(new Date().getFullYear()); </script> CircuitVerse, All rights reserved.</div>
        <div class="d-none d-sm-none d-md-none d-lg-none d-xl-block copyright pl-3" >Copyright © <script type="text/javascript"> document.write(new Date().getFullYear()); </script> CircuitVerse, All rights reserved.</div>
     </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="/">
    <%= image_tag("cvlogo.svg", class: "logo", alt: "CircuitVerse Logo") %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsedNavbar"
          aria-controls="collapsedNavbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="collapsedNavbar">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0 navigationBar-item">
      <li class="nav-item px-1">
        <a class="btn btn-outline-success rounded-0 simulator text-dark " href="/simulator">Simulator</a>
      </li>
      <li class="nav-item px-1">
        <a class="nav-link text-dark" href="https://learn.circuitverse.org/">Learn</a>
      </li>
      <li class="nav-item px-1">
        <a class="nav-link text-dark" href="https://docs.circuitverse.org/">Documentation</a>
      </li>
      <li class="nav-item px-1 <%= request.path == '/examples' ? 'active' : '' %>">
        <a class="nav-link text-dark" href="/examples">Examples</a>
      </li>
      <li class="nav-item px-1 <%= request.path == '/contribute' ? 'active' : '' %>">
        <a class="nav-link text-dark" href="/contribute">Contribute</a>
      </li>
      <li class="nav-item px-1 <%= request.path == '/teachers' ? 'active' : '' %>">
        <a class="nav-link text-dark" href="/teachers">Teachers</a>
      </li>
      <li class="nav-item px-1 <%= request.path == '/about' ? 'active' : '' %>">
        <a class="nav-link text-dark" href="/about">About</a>
      </li>
      <% if user_signed_in? %>
       <div class="navbar-nav nav-item dropdown">
        <li class="nav-item px-1">
          <a class="nav-link text-dark dropdown-toggle" style="cursor: pointer;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="navbar-username-truncate"><%= current_user.name %></div>
         </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= profile_path(current_user) %>">Profile </a>
          <a class="dropdown-item" href="<%= notifications_path(current_user) %>">Notifications </a>
          <a class="dropdown-item" href="<%= user_path(current_user) %>">My Circuits</a>
          <a class="dropdown-item" href="<%= user_groups_path(current_user) %>">My Groups</a>
          <a class="dropdown-item" href="<%= user_favourites_path(current_user) %>">My Favourites</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" rel="nofollow" data-method="delete" href="<%= destroy_user_session_path %>">Sign Out</a>

        </div>
        </li>
      <% else %>
        <li class="nav-item px-2 <%= request.path == '/users/sign_in' ? 'active' : '' %>">
          <a class="nav-link text-dark" href="/users/sign_in">Login</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>